import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, Link as LinkIcon, Mail, Share2 } from 'lucide-react'
import { BlogSidebar } from '@/components/blog-sidebar'
import { formatDate, getPostCategories, getFeaturedImage, stripHtml, type WpPost } from '@/lib/wordpress'

export function BlogPost({ post, recent }: { post: WpPost; recent: WpPost[] }) {
  const image = getFeaturedImage(post)
  return <><main className="mx-auto grid max-w-6xl gap-14 px-5 py-10 lg:grid-cols-[minmax(0,1fr)_300px] lg:gap-16 lg:px-8 lg:py-16"><article><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-primary"><ArrowLeft aria-hidden="true" className="size-4" /> Back to all stories</Link><div className="flex items-center gap-3 text-xs font-bold uppercase tracking-[0.15em] text-primary"><span>{stripHtml(getPostCategories(post)[0]?.name || 'Insights')}</span><span className="text-border">/</span><time dateTime={post.date}>{formatDate(post.date)}</time></div><h1 className="mt-5 max-w-4xl font-serif text-4xl font-bold leading-[1.05] tracking-tight md:text-6xl">{stripHtml(post.title.rendered)}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{stripHtml(post.excerpt.rendered)}</p>{image && <div className="relative mt-10 aspect-[16/9] overflow-hidden bg-muted"><Image src={image} alt={post._embedded?.['wp:featuredmedia']?.[0]?.alt_text || stripHtml(post.title.rendered)} fill sizes="(max-width: 1024px) 100vw, 760px" className="object-cover" unoptimized /></div>}<div className="mt-10 flex items-start gap-8"><div className="hidden flex-col gap-3 md:flex" aria-label="Share this story"><span className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Share</span><a className="flex size-9 items-center justify-center rounded-full border border-border hover:border-primary hover:text-primary" href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(post.link)}`} target="_blank" rel="noreferrer" aria-label="Share on LinkedIn"><LinkIcon className="size-4" /></a><a className="flex size-9 items-center justify-center rounded-full border border-border hover:border-primary hover:text-primary" href={`mailto:?subject=${encodeURIComponent(stripHtml(post.title.rendered))}&body=${encodeURIComponent(post.link)}`} aria-label="Share by email"><Mail className="size-4" /></a><a className="flex size-9 items-center justify-center rounded-full border border-border hover:border-primary hover:text-primary" href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(post.link)}`} target="_blank" rel="noreferrer" aria-label="Share on Facebook"><Share2 className="size-4" /></a></div><div className="prose prose-lg max-w-none text-foreground prose-headings:font-serif prose-headings:tracking-tight prose-a:text-primary prose-img:w-full" dangerouslySetInnerHTML={{ __html: post.content.rendered }} /></div></article><BlogSidebar recent={recent} /></main></>
}
