import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight, Clock3 } from 'lucide-react'
import { formatDate, getAuthor, getPostCategories, getFeaturedImage, getReadingTime, stripHtml, type WpPost } from '@/lib/wordpress'

export function BlogCard({ post, featured = false }: { post: WpPost; featured?: boolean }) {
  const image = getFeaturedImage(post); const category = stripHtml(getPostCategories(post)[0]?.name || 'Insights'); const title = stripHtml(post.title.rendered); const excerpt = stripHtml(post.excerpt.rendered); const author = getAuthor(post)
  return <article className="group overflow-hidden rounded-2xl border border-border bg-card shadow-lg shadow-foreground/5 transition-all duration-300 hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl hover:shadow-primary/10"><Link href={`/${post.slug}`} className="relative block aspect-[423/280] overflow-hidden bg-muted">{image ? <Image src={image} alt={post._embedded?.['wp:featuredmedia']?.[0]?.alt_text || title} fill sizes={featured ? '(max-width: 1024px) 100vw, 860px' : '(max-width: 768px) 100vw, 394px'} className="object-cover transition-transform duration-700 group-hover:scale-105" unoptimized priority={featured} /> : <div className="absolute inset-0 bg-muted" />}</Link><div className="flex flex-col gap-3 p-6 lg:p-7"><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-[0.12em] text-primary"><span className="rounded-full bg-accent px-2.5 py-1">{category}</span><time dateTime={post.date}>{formatDate(post.date)}</time></div><Link href={`/${post.slug}`} className="flex items-start justify-between gap-3"><h2 className={featured ? 'text-balance text-[27px] font-bold leading-[1.2] tracking-[-0.03em] text-card-foreground md:text-[33px]' : 'text-balance text-[21px] font-bold leading-[1.28] tracking-[-0.02em] text-card-foreground'}>{title}</h2><ArrowUpRight aria-hidden="true" className="mt-1 size-5 shrink-0 text-primary transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link><p className="text-[13px] leading-6 text-muted-foreground">{excerpt.slice(0, featured ? 230 : 150)}{excerpt.length > (featured ? 230 : 150) ? '…' : ''}</p><div className="flex items-center justify-between gap-3 border-t border-border pt-3 text-[11px] font-medium text-muted-foreground"><span className="inline-flex min-w-0 items-center gap-2"><span className="relative size-6 shrink-0 overflow-hidden rounded-full bg-muted">{author.avatar_urls?.['48'] && <Image src={author.avatar_urls['48']} alt="" fill sizes="24px" className="object-cover" unoptimized />}</span><span className="truncate">{author.name || 'imeetify team'}</span></span><span className="inline-flex shrink-0 items-center gap-1"><Clock3 className="size-3.5" /> {getReadingTime(post.content.rendered)} min</span></div></div></article>
}
