import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, Link as LinkIcon, Mail, Share2 } from 'lucide-react'
import { BlogSidebar } from '@/components/blog-sidebar'
import { formatDate, getPostCategories, getFeaturedImage, stripHtml, type WpPost } from '@/lib/wordpress'

export function BlogPost({ post, recent }: { post: WpPost; recent: WpPost[] }) {
  const image = getFeaturedImage(post)
  const title = stripHtml(post.title.rendered)
  return <main className="mx-auto grid max-w-[1260px] gap-10 px-5 py-10 lg:grid-cols-[minmax(0,1fr)_300px] lg:gap-12 lg:px-8 lg:py-14"><article className="min-w-0"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-[#647087] hover:text-[#54bd70]"><ArrowLeft aria-hidden="true" className="size-4" /> Back to all stories</Link><div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-[#54bd70]"><span>{stripHtml(getPostCategories(post)[0]?.name || 'Insights')}</span><span className="text-[#9aa5b5]">|</span><time dateTime={post.date}>{formatDate(post.date)}</time></div><h1 className="mt-5 max-w-4xl text-balance text-[38px] font-bold leading-[1.15] text-[#17253d] md:text-[52px]">{title}</h1><p className="mt-5 max-w-3xl text-[16px] leading-7 text-[#647087]">{stripHtml(post.excerpt.rendered)}</p>{image && <div className="relative mt-9 aspect-[16/9] overflow-hidden rounded-[10px] bg-[#eef1f5]"><Image src={image} alt={post._embedded?.['wp:featuredmedia']?.[0]?.alt_text || title} fill sizes="(max-width: 1024px) 100vw, 860px" className="object-cover" unoptimized /></div>}<div className="mt-9 flex items-start gap-7"><div className="hidden flex-col gap-3 md:flex" aria-label="Share this story"><span className="text-[10px] font-semibold uppercase tracking-widest text-[#8994a6]">Share</span><a className="flex size-9 items-center justify-center rounded-full border border-[#dce2e9] text-[#17253d] hover:border-[#54bd70] hover:text-[#54bd70]" href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(post.link)}`} target="_blank" rel="noreferrer" aria-label="Share on LinkedIn"><LinkIcon className="size-4" /></a><a className="flex size-9 items-center justify-center rounded-full border border-[#dce2e9] text-[#17253d] hover:border-[#54bd70] hover:text-[#54bd70]" href={`mailto:?subject=${encodeURIComponent(title)}&body=${encodeURIComponent(post.link)}`} aria-label="Share by email"><Mail className="size-4" /></a><a className="flex size-9 items-center justify-center rounded-full border border-[#dce2e9] text-[#17253d] hover:border-[#54bd70] hover:text-[#54bd70]" href={post.link} target="_blank" rel="noreferrer" aria-label="Open original post"><Share2 className="size-4" /></a></div><div className="prose max-w-none flex-1" dangerouslySetInnerHTML={{ __html: post.content.rendered }} /></div></article><BlogSidebar recent={recent} /></main>
}
